import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import toast from 'react-hot-toast'
import { useQuery } from '@tanstack/react-query'
import { api, apiClient } from '../api'
import './FormPages.css'

type Ingredient = { id:number; name:string; default_unit?:string|null }
type RecipeIngredient = { ingredient_id:number; name:string; quantity:string; unit:string }
type Instruction = { instruction_text:string; timer_seconds:number; tip:string }
const units=['g','kg','mg','ml','l','oz','tsp','tbsp','cup','piece']
const unwrap=(value:any):any[]=>Array.isArray(value)?value:Array.isArray(value?.items)?value.items:Array.isArray(value?.data)?value.data:Array.isArray(value?.results)?value.results:[]
const duration=(value:number)=>Math.max(0,Number(value)||0)

export function RecipeFormPage(){
  const navigate=useNavigate(); const {recipeId}=useParams(); const isEdit=Boolean(recipeId); const [step,setStep]=useState(0); const [mode,setMode]=useState<'normal'|'recording'>('recording'); const [saving,setSaving]=useState(false)
  const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [prep,setPrep]=useState(0); const [cook,setCook]=useState(0); const [servings,setServings]=useState('2'); const [visibility,setVisibility]=useState<'PRIVATE'|'PUBLIC'>('PRIVATE'); const [cookedWeight,setCookedWeight]=useState(''); const [cookedUnit,setCookedUnit]=useState('g'); const [categoryIds,setCategoryIds]=useState<number[]>([]); const [tags,setTags]=useState('')
  const [ingredients,setIngredients]=useState<RecipeIngredient[]>([]); const [ingredientSearch,setIngredientSearch]=useState(''); const [instructions,setInstructions]=useState<Instruction[]>([{instruction_text:'',timer_seconds:0,tip:''}])
  const recipeQuery=useQuery({queryKey:['recipe-form',recipeId],queryFn:async()=>(await api.recipes.get(recipeId!)).data,enabled:isEdit})
  const ingredientQuery=useQuery({queryKey:['ingredients-form',ingredientSearch],queryFn:async()=>(await api.ingredients.search(ingredientSearch)).data,enabled:ingredientSearch.trim().length>0})
  const ingredientListQuery=useQuery({queryKey:['ingredients-form-list'],queryFn:async()=>(await api.ingredients.list(1,100)).data})
  const categoryQuery=useQuery({queryKey:['categories-form'],queryFn:async()=>(await api.categories.list(1,100)).data})
  const availableIngredients=useMemo(()=>unwrap(ingredientSearch.trim()?ingredientQuery.data:ingredientListQuery.data),[ingredientSearch,ingredientQuery.data,ingredientListQuery.data])
  const categories=useMemo(()=>unwrap(categoryQuery.data),[categoryQuery.data])

  useEffect(()=>{ if(!isEdit||!recipeQuery.data)return; const r=recipeQuery.data?.data??recipeQuery.data?.recipe??recipeQuery.data; setName(r.name??'');setDescription(r.description??'');setPrep(duration(r.preparation_time));setCook(duration(r.cooking_time));setServings(String(r.servings??2));setVisibility(r.visibility==='PUBLIC'?'PUBLIC':'PRIVATE');setCookedWeight(r.cooked_weight_amount?String(r.cooked_weight_amount):'');setCookedUnit(r.cooked_weight_unit??'g');setCategoryIds(Array.isArray(r.category_ids)?r.category_ids:[]);setTags(Array.isArray(r.tag_names)?r.tag_names.join(', '):'');setIngredients((r.ingredients??[]).map((x:any,i:number)=>({ingredient_id:Number(x.ingredient_id),name:x.name??`Ingredient ${i+1}`,quantity:String(x.quantity??1),unit:x.unit??'g'})));setInstructions((r.instructions??[]).length?(r.instructions??[]).map((x:any)=>({instruction_text:x.instruction_text??'',timer_seconds:Number(x.timer_seconds)||0,tip:x.tip??''})):[{instruction_text:'',timer_seconds:0,tip:''}]) },[isEdit,recipeQuery.data])

  const toggleIngredient=(item:Ingredient)=>{ const id=Number(item.id); if(ingredients.some(x=>x.ingredient_id===id)){setIngredients(ingredients.filter(x=>x.ingredient_id!==id));return} setIngredients([...ingredients,{ingredient_id:id,name:item.name,quantity:'1',unit:item.default_unit||'g'}]) }
  const updateIngredient=(i:number,key:'quantity'|'unit',value:string)=>setIngredients(ingredients.map((x,index)=>index===i?{...x,[key]:value}:x))
  const updateInstruction=(i:number,key:keyof Instruction,value:string|number)=>setInstructions(instructions.map((x,index)=>index===i?{...x,[key]:value}:x))
  const submit=async()=>{ if(!name.trim())return toast.error('Recipe name is required'); if(!ingredients.length)return toast.error('Add at least one ingredient'); if(!instructions.some(x=>x.instruction_text.trim()))return toast.error('Add at least one cooking step'); const servingCount=Math.max(1,Number(servings)||1); const payload:any={name:name.trim(),description:description.trim()||null,preparation_time:duration(prep),cooking_time:duration(cook),total_time:duration(prep)+duration(cook),servings:servingCount,visibility,ingredients:ingredients.map((x,i)=>({ingredient_id:x.ingredient_id,name:x.name,quantity:Number(x.quantity)||0,unit:x.unit,display_order:i+1})),instructions:instructions.filter(x=>x.instruction_text.trim()).map((x,i)=>({step_number:i+1,instruction_text:x.instruction_text.trim(),timer_seconds:Number(x.timer_seconds)||0,tip:x.tip.trim()||null})),category_ids:categoryIds,tag_names:tags.split(',').map(x=>x.trim()).filter(Boolean)}; if(cookedWeight){payload.cooked_weight_amount=Number(cookedWeight);payload.cooked_weight_unit=cookedUnit} setSaving(true);try{if(isEdit)await apiClient.put(`/api/v1/recipes/${recipeId}`,payload);else await apiClient.post('/api/v1/recipes/',payload);toast.success(isEdit?'Recipe updated':'Recipe created');navigate('/recipes')}catch(error:any){toast.error(error?.response?.data?.detail||`Unable to ${isEdit?'update':'create'} recipe`)}finally{setSaving(false)}}
  const stepNames=['Basics','Ingredients','Instructions']
  const section=<>
    <section className="form-card"><div className="form-card-head"><div><span className="form-kicker">STEP 01</span><h2>Recipe basics</h2><p>Name, timing, servings and visibility.</p></div></div><div className="form-grid"><label className="field field-wide"><span>Recipe name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Creamy garlic pasta" /></label><label className="field field-wide"><span>Description</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Tell people what makes this recipe special" rows={4}/></label><label className="field"><span>Preparation time (min)</span><input type="number" min="0" value={prep||''} onChange={e=>setPrep(Number(e.target.value)||0)}/></label><label className="field"><span>Cooking time (min)</span><input type="number" min="0" value={cook||''} onChange={e=>setCook(Number(e.target.value)||0)}/></label><label className="field"><span>Servings</span><input type="number" min="1" value={servings} onChange={e=>setServings(e.target.value)}/></label><label className="field"><span>Visibility</span><select value={visibility} onChange={e=>setVisibility(e.target.value as any)}><option value="PRIVATE">Private</option><option value="PUBLIC">Public</option></select></label></div><div className="choice-row"><button className={visibility==='PRIVATE'?'choice active':''} onClick={()=>setVisibility('PRIVATE')}>🔒 Private</button><button className={visibility==='PUBLIC'?'choice active':''} onClick={()=>setVisibility('PUBLIC')}>🌐 Public</button></div><div className="sub-card"><div><strong>Final cooked quantity</strong><span>Enter the final amount after cooking.</span></div><div className="inline-fields"><input type="number" min="0" value={cookedWeight} onChange={e=>setCookedWeight(e.target.value)} placeholder="Amount"/><select value={cookedUnit} onChange={e=>setCookedUnit(e.target.value)}>{['kg','g','mg','l','ml','oz'].map(u=><option key={u}>{u}</option>)}</select></div></div><label className="field"><span>Tags</span><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="healthy, quick, dinner"/><small>Separate tags with commas.</small></label><div><span className="field-label">Categories</span><div className="chip-list">{categories.map((c:any)=>{const id=Number(c.id);return <button type="button" key={id} className={`chip ${categoryIds.includes(id)?'selected':''}`} onClick={()=>setCategoryIds(categoryIds.includes(id)?categoryIds.filter(x=>x!==id):[...categoryIds,id])}>{c.name??c.title}</button>})}</div></div></section>
    <section className="form-card"><div className="form-card-head"><div><span className="form-kicker">STEP 02</span><h2>Ingredients</h2><p>Add ingredients, quantities and units.</p></div><span className="count-pill">{ingredients.length}</span></div><div className="search-field"><span>⌕</span><input value={ingredientSearch} onChange={e=>setIngredientSearch(e.target.value)} placeholder="Search ingredients..."/></div>{availableIngredients.length>0&&<div className="picker-list">{availableIngredients.slice(0,12).map((item:any)=><button key={item.id} type="button" className={ingredients.some(x=>x.ingredient_id===Number(item.id))?'picked':''} onClick={()=>toggleIngredient(item)}><span>{ingredients.some(x=>x.ingredient_id===Number(item.id))?'✓':'+'}</span>{item.name}</button>)}</div>}<div className="editable-list">{ingredients.map((item,i)=><div className="editable-row" key={`${item.ingredient_id}-${i}`}><div className="row-index">{i+1}</div><strong>{item.name}</strong><input value={item.quantity} onChange={e=>updateIngredient(i,'quantity',e.target.value)} aria-label="Quantity"/><select value={item.unit} onChange={e=>updateIngredient(i,'unit',e.target.value)}>{units.map(u=><option key={u}>{u}</option>)}</select><button type="button" className="danger-icon" onClick={()=>setIngredients(ingredients.filter((_,n)=>n!==i))}>×</button></div>)}</div>{!ingredients.length&&<div className="empty-picker">No ingredients added yet.</div>}</section>
    <section className="form-card"><div className="form-card-head"><div><span className="form-kicker">STEP 03</span><h2>Cooking instructions</h2><p>Add each cooking step, optional timer and tip.</p></div></div><div className="step-list">{instructions.map((item,i)=><div className="instruction-card" key={i}><div className="instruction-number">{i+1}</div><div className="instruction-body"><textarea value={item.instruction_text} onChange={e=>updateInstruction(i,'instruction_text',e.target.value)} placeholder="Describe what to do..." rows={3}/><div className="instruction-meta"><label>Timer (sec)<input type="number" min="0" value={item.timer_seconds||''} onChange={e=>updateInstruction(i,'timer_seconds',Number(e.target.value)||0)}/></label><label>Tip<input value={item.tip} onChange={e=>updateInstruction(i,'tip',e.target.value)} placeholder="Optional tip"/></label>{instructions.length>1&&<button type="button" className="danger-button" onClick={()=>setInstructions(instructions.filter((_,n)=>n!==i))}>Remove</button>}</div></div></div>)}</div><button type="button" className="add-button" onClick={()=>setInstructions([...instructions,{instruction_text:'',timer_seconds:0,tip:''}])}>＋ Add cooking step</button></section>
  </>
  return <div className="form-page"><div className="form-hero"><div><span className="form-kicker">{isEdit?'EDIT RECIPE':'CREATE RECIPE'}</span><h1>{isEdit?'Edit recipe':'Create a recipe'}</h1><p>Build your recipe the same way you do in MUVETH Kitchen mobile.</p></div><button className="ghost-button" onClick={()=>navigate(-1)}>Cancel</button></div><div className="creation-mode"><span>Creation mode</span><button className={mode==='normal'?'active':''} onClick={()=>setMode('normal')}>Normal</button><button className={mode==='recording'?'active':''} onClick={()=>setMode('recording')}>Recording</button></div>{mode==='recording'&&<div className="wizard-progress">{stepNames.map((x,i)=><button key={x} className={step===i?'active':step>i?'done':''} onClick={()=>i<=step&&setStep(i)}><span>{step>i?'✓':i+1}</span>{x}</button>)}</div>}<div className="form-stack">{mode==='normal'?section:[section.split?null:null]}</div>{mode==='normal'?null:<div className="recording-step-content">{step===0?<section className="form-card">{section.props?.children?.[0]??null}</section>:step===1?<section className="form-card">{section.props?.children?.[1]??null}</section>:<section className="form-card">{section.props?.children?.[2]??null}</section>}</div>}<div className="form-actions"><button className="ghost-button" onClick={()=>step>0&&mode==='recording'?setStep(step-1):navigate(-1)}>{step>0&&mode==='recording'?'← Back':'Cancel'}</button>{mode==='recording'&&step<2?<button className="primary-form-button" onClick={()=>setStep(step+1)}>Continue →</button>:<button className="primary-form-button" disabled={saving} onClick={submit}>{saving?'Saving…':isEdit?'✓ Save changes':'✓ Save recipe'}</button>}</div></div>
}
