import { useEffect, useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useParams } from 'react-router-dom'
import toast from 'react-hot-toast'
import { api } from '../api'

type AnyRecord = Record<string, any>
type NutritionItem = { code: string; name: string; amount: number; unit: string; type?: string }
function formatTime(minutes: any) { const n = Number(minutes); return Number.isFinite(n) && n > 0 ? `${n} min` : '—' }
function labelize(value: string) { return String(value).replace(/[_-]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) }
function nutritionValue(value: any): string { if (value == null) return '—'; if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') return String(value); if (Array.isArray(value)) return value.map(nutritionValue).join(', '); if (typeof value === 'object') return Object.entries(value).map(([k,v]) => `${labelize(k)}: ${nutritionValue(v)}`).join(' • '); return String(value) }
function nutritionItems(data: AnyRecord): NutritionItem[] { return Array.isArray(data?.items) ? data.items.map((item: AnyRecord) => ({ code:String(item.code ?? ''), name:String(item.name ?? ''), amount:Number(item.amount), unit:String(item.unit ?? ''), type:item.type })).filter((item: NutritionItem) => Number.isFinite(item.amount) && item.amount > 0 && item.name) : [] }
function normalizedName(item: NutritionItem) { const name=item.name.toLowerCase(); const code=item.code.toUpperCase(); if (code.includes('CARBOHYDRATE') || code==='CARBS' || name.includes('carbohydrate')) return 'Carbs'; if (code.includes('TOTAL_FAT') || code==='FAT' || name.includes('total lipid') || name==='fat') return 'Fat'; if (code==='PROTEIN' || name==='protein') return 'Protein'; if (code==='FIBER' || name.includes('fiber')) return 'Fiber'; return item.name }
function isEnergy(item: NutritionItem) { const code=item.code.toUpperCase(); const name=item.name.toLowerCase(); return ['CALORIES','CALORIE','ENERGY','KCAL'].includes(code) || name==='energy' || name.startsWith('energy ') }
function isMacro(item: NutritionItem) { return String(item.type ?? '').toLowerCase()==='macro' || ['PROTEIN','CARBS','CARBOHYDRATES','CARBOHYDRATE','FAT','TOTAL_FAT','FIBER','DIETARY_FIBER'].includes(item.code.toUpperCase()) }
function formatNutritionAmount(amount:number, unit:string) { const rounded=amount<10?Math.round(amount*10)/10:Math.round(amount); const display=Number.isInteger(rounded)?String(rounded):rounded.toFixed(1); const u=unit.toLowerCase(); if(u==='kcal'||u==='cal') return `${display} kcal`; if(u==='g') return `${display}g`; if(u==='mg') return `${display}mg`; if(u==='mcg'||u==='ug'||u==='µg') return `${display}mcg`; return `${display} ${unit}` }
function NutritionSection({ nutrition, scale, portionLabel }: { nutrition: AnyRecord; scale:number; portionLabel:string }) { const items=nutritionItems(nutrition).map(item=>({...item,amount:item.amount*scale)); const main=items.filter(isEnergy); const macros=items.filter(item=>!isEnergy(item)&&isMacro(item)); const micros=items.filter(item=>!isEnergy(item)&&!isMacro(item)); if(!items.length)return null; const order=['PROTEIN','CARBOHYDRATES','CARBS','FAT','TOTAL_FAT','FIBER']; macros.sort((a,b)=>(order.indexOf(a.code.toUpperCase())<0?99:order.indexOf(a.code.toUpperCase()))-(order.indexOf(b.code.toUpperCase())<0?99:order.indexOf(b.code.toUpperCase()))); return <section className="nutrition-panel"><div className="nutrition-panel-header"><h3>Nutrition</h3><span>{portionLabel}</span></div><div className="nutrition-panel-card">{main.length>0&&<div className="nutrition-subsection"><h4>Main</h4><div className="nutrition-hero-list">{main.map(item=><div className="nutrition-hero-item" key={`${item.code}-${item.name}`}><i/><strong>{formatNutritionAmount(item.amount,item.unit)}</strong><span>{normalizedName(item)}</span></div>)}</div></div>}{macros.length>0&&<div className="nutrition-subsection"><h4>Macros</h4><div className="nutrition-card-grid">{macros.map(item=><div className="nutrition-card-item" key={`${item.code}-${item.name}`}><i/><strong>{formatNutritionAmount(item.amount,item.unit)}</strong><span>{normalizedName(item)}</span></div>)}</div></div>}{micros.length>0&&<div className="nutrition-subsection"><h4>Micros</h4><div className="nutrition-micro-grid">{micros.map(item=><div className="nutrition-micro-item" key={`${item.code}-${item.name}`}><div><i/><span>{normalizedName(item)}</span></div><strong>{formatNutritionAmount(item.amount,item.unit)}</strong></div>)}</div></div>}</div></section> }
export function RecipeDetailPage() {
 const { recipeId }=useParams(); const [portionMode,setPortionMode]=useState<'servings'|'quantity'>('servings'); const [portionValue,setPortionValue]=useState(1); const [checkedIngredients,setCheckedIngredients]=useState<Record<number,boolean>>({}); const [completedSteps,setCompletedSteps]=useState<Record<number,boolean>>({}); const [rating,setRating]=useState<number|null>(null); const [cookMode,setCookMode]=useState(false); const [cookStep,setCookStep]=useState(0)
 const query=useQuery({queryKey:['recipe-detail',recipeId],queryFn:async()=>(await api.recipes.get(recipeId!)).data,enabled:!!recipeId}); const recipe:AnyRecord|undefined=query.data?.data??query.data?.recipe??query.data; const ingredients=useMemo(()=>recipe?.ingredients??[],[recipe]); const instructions=useMemo(()=>recipe?.instructions??recipe?.steps??[],[recipe]); const nutrition=recipe?.nutrition??recipe?.nutrition_summary??{}; const baseServings=Math.max(1,Number(recipe?.servings)||1); const totalQuantity=Number(recipe?.cooked_weight_amount??recipe?.total_quantity??recipe?.total_weight_amount)||0; const quantityUnit=String(recipe?.cooked_weight_unit??recipe?.total_quantity_unit??'g'); useEffect(()=>{if(recipe){setPortionMode('servings');setPortionValue(baseServings)}},[recipe?.id,baseServings]); const scale=portionMode==='servings'?portionValue/baseServings:(totalQuantity>0?portionValue/totalQuantity:1); const portionLabel=portionMode==='servings'?`Per ${Math.round(portionValue)} serving${Math.round(portionValue)===1?'':'s'}`:`Per ${portionValue} ${quantityUnit}`; const name=recipe?.name??recipe?.title??'Recipe'; const setRatingValue=(value:number)=>{setRating(value);toast.success(`You rated this recipe ${value} star${value>1?'s':''}.`)}
 if(query.isLoading)return <div className="detail-loading"><div className="detail-spinner"/><p>Loading recipe…</p></div>; if(query.isError||!recipe)return <div className="detail-error"><div className="detail-error-icon">!</div><h2>Couldn’t load recipe</h2><p>Please try again.</p><button onClick={()=>query.refetch()}>Retry</button></div>
 const activeInstruction=instructions[cookStep]; const activeText=typeof activeInstruction==='string'?activeInstruction:activeInstruction?.instruction_text??activeInstruction?.text??''
 return <div className="detail-page"><section className="recipe-hero-detail"><div className="recipe-detail-image">{recipe.image_url||recipe.image_urls?.[0]?<img src={recipe.image_url||recipe.image_urls?.[0]} alt={name}/>:<span>🥗</span>}</div><div className="recipe-detail-copy"><p className="detail-eyebrow">RECIPE</p><h2>{name}</h2>{recipe.description?<p className="detail-description">{recipe.description}</p>:null}<div className="recipe-meta-grid"><div><strong>◷</strong><span>Prep<br/><b>{formatTime(recipe.preparation_time??recipe.prep_time)}</b></span></div><div><strong>🔥</strong><span>Cook<br/><b>{formatTime(recipe.cooking_time??recipe.cook_time)}</b></span></div><div><strong>◉</strong><span>Total<br/><b>{formatTime(recipe.total_time)}</b></span></div><div><strong>♟</strong><span>Servings<br/><b>{baseServings}</b></span></div></div>{recipe.category?.name||recipe.category?<span className="detail-category">{typeof recipe.category==='string'?recipe.category:recipe.category.name}</span>:null}</div></section>
 <section className="detail-card portion-card-mobile"><h3>Adjust Portion</h3><p>{portionMode==='servings'?`Original recipe makes ${baseServings} serving${baseServings===1?'':'s'}`:`Total recipe quantity: ${totalQuantity||'—'} ${quantityUnit}`}</p><div className="portion-mode-row"><button className={portionMode==='servings'?'active':''} onClick={()=>setPortionMode('servings')} disabled={baseServings<=0}>◉ <span>Servings</span></button><button className={portionMode==='quantity'?'active':''} onClick={()=>setPortionMode('quantity')} disabled={totalQuantity<=0}>◫ <span>Quantity</span></button></div><div className="portion-control-mobile"><button onClick={()=>setPortionValue(v=>Math.max(1,v-1))}>−</button><div><strong>{portionValue}</strong><span>{portionMode==='servings'?(portionValue===1?'serving':'servings'):quantityUnit}</span></div><button onClick={()=>setPortionValue(v=>v+1)}>+</button></div></section>
 <section className="detail-section"><div className="section-heading"><div><p className="section-kicker">INGREDIENTS</p><h3>Ingredients</h3></div><span>{ingredients.length}</span></div><div className="ingredient-list">{ingredients.length?ingredients.map((item:AnyRecord,index:number)=>{const checked=!!checkedIngredients[index];const n=Number(item.quantity);const scaled=Number.isFinite(n)?Math.round(n*scale*100)/100:item.quantity;return <button className={`ingredient-row ${checked?'checked':''}`} key={index} onClick={()=>setCheckedIngredients(v=>({...v,[index]:!v[index]}))}><span className="check-circle">{checked?'✓':''}</span><span className="ingredient-name">{item.name||item.ingredient_name||`Ingredient ${index+1}`}</span><strong>{scaled??''} {item.unit||''}</strong></button>}):<div className="empty-detail">No ingredients available.</div>}</div></section>
 <NutritionSection nutrition={nutrition} scale={scale} portionLabel={portionLabel}/>
 <section className="detail-section"><div className="section-heading"><div><p className="section-kicker">METHOD</p><h3>Instructions</h3></div><span>{instructions.length}</span></div><div className="instruction-list">{instructions.length?instructions.map((step:any,index:number)=>{const text=typeof step==='string'?step:step.instruction_text??step.text??'';const done=!!completedSteps[index];return <div className={`instruction-row ${done?'completed':''}`} key={index}><button className="step-check" onClick={()=>setCompletedSteps(v=>({...v,[index]:!v[index]}))}>{done?'✓':index+1}</button><div><p>{text}</p>{step?.tip?<small>Tip: {nutritionValue(step.tip)}</small>:null}{step?.timer_seconds?<span className="timer-pill">◷ {Math.ceil(step.timer_seconds/60)} min</span>:null}</div></div>}):<div className="empty-detail">No instructions available.</div>}</div></section>
 <section className="cook-card"><div><p className="section-kicker">READY?</p><h3>Cook with confidence.</h3><p>Follow the recipe step by step with ingredients and timers in one place.</p></div><button onClick={()=>{setCookMode(true);setCookStep(0)}}>▶ Start Cooking</button></section><section className="detail-section rating-section"><div><p className="section-kicker">YOUR RATING</p><h3>How was this recipe?</h3></div><div className="stars">{[1,2,3,4,5].map(value=><button key={value} className={rating&&value<=rating?'selected':''} onClick={()=>setRatingValue(value)}>★</button>)}</div></section>{cookMode&&<div className="cook-overlay"><div className="cook-modal"><div className="cook-modal-head"><div><p className="section-kicker">COOK MODE</p><h2>Step {cookStep+1} of {Math.max(instructions.length,1)}</h2></div><button onClick={()=>setCookMode(false)}>×</button></div><div className="cook-progress"><span style={{width:`${instructions.length?((cookStep+1)/instructions.length)*100:100}%`}}/></div><p className="cook-instruction">{activeText||'No cooking step available.'}</p>{activeInstruction?.tip?<div className="cook-tip">Tip: {nutritionValue(activeInstruction.tip)}</div>:null}{activeInstruction?.timer_seconds?<div className="cook-timer">◷ {Math.ceil(activeInstruction.timer_seconds/60)} min</div>:null}<div className="cook-controls"><button disabled={cookStep===0} onClick={()=>setCookStep(s=>Math.max(0,s-1))}>← Previous</button><button onClick={()=>cookStep>=instructions.length-1?setCookMode(false):setCookStep(s=>s+1)}>{cookStep>=instructions.length-1?'Finish':'Next →'}</button></div></div></div>}</div>
}
