import { useState } from 'react'
import toast from 'react-hot-toast'
import { keycloak } from '../keycloak'

export function SettingsPage() {
  const [notifications, setNotifications] = useState(true)
  const [compact, setCompact] = useState(false)
  const save = () => toast.success('Settings saved')
  return <div className="mx-auto max-w-3xl"><p className="text-xs font-bold tracking-[.25em] text-sage">PREFERENCES</p><h1 className="mt-2 font-display text-4xl md:text-5xl">Settings</h1><p className="mt-2 text-slate-500">Make MUVETH Kitchen feel like yours.</p><div className="mt-8 space-y-4"><section className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-black/5"><p className="text-xs font-bold tracking-widest text-sage">ACCOUNT</p><div className="mt-5 flex items-center justify-between"><div><h2 className="font-semibold">Signed in</h2><p className="mt-1 text-sm text-slate-500">Authentication is managed securely by Keycloak.</p></div><span className="rounded-full bg-[#edf1e9] px-3 py-1 text-xs font-bold text-moss">SECURE</span></div></section><section className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-black/5"><p className="text-xs font-bold tracking-widest text-sage">PREFERENCES</p><div className="mt-5 divide-y divide-black/5"><label className="flex cursor-pointer items-center justify-between py-4"><div><p className="font-semibold">Cooking notifications</p><p className="text-sm text-slate-500">Receive useful kitchen reminders.</p></div><input type="checkbox" checked={notifications} onChange={e => setNotifications(e.target.checked)} className="h-5 w-5 accent-[#3d513f]" /></label><label className="flex cursor-pointer items-center justify-between py-4"><div><p className="font-semibold">Compact recipe cards</p><p className="text-sm text-slate-500">Show more recipes at once.</p></div><input type="checkbox" checked={compact} onChange={e => setCompact(e.target.checked)} className="h-5 w-5 accent-[#3d513f]" /></label></div></section><div className="flex justify-end"><button onClick={save} className="rounded-full bg-ink px-6 py-3 text-sm font-semibold text-white">Save settings</button></div><button onClick={() => keycloak.logout({ redirectUri: window.location.origin })} className="w-full rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-left text-sm font-semibold text-red-600">Sign out of MUVETH Kitchen</button></div></div>
}
